context.modules = [
    {   name = libpipewire-module-filter-chain
        args = {
            node.description = "Upmix Test Sink"
            node.name = "Upmix_Test"
            filter.graph = {
                nodes = [ { type = builtin name = copy label = copy } ]
                inputs = [ "copy:In" ]
                outputs = [ "copy:Out" ]
            }
            capture.props = { media.class = "Audio/Sink" }
        }
    }
]
